export interface PatientRegister{
    name: string,
    lastname: string,
    phone: string,
    email: string,
    cc: string,
    password: string,
    gender: string,
    image_file: File,
    birthdate: Date,
    address: string,
    description: string,
    familiar_name: string,
    familiar_lastname: string,
    familiar_email: string,
    familiar_phone: string,
}